USE RECPAPAGAIOS
GO

DROP TABLE IF EXISTS HOSPEDE;

CREATE TABLE HOSPEDE
(
	HSP_ID_INT INT NOT NULL IDENTITY(1,1),
	HSP_NOME_STR VARCHAR(255),
	HSP_CPF_CHAR CHAR(11),
	HSP_DTNASC_DATE DATE,
	HSP_EMAIL_STR VARCHAR(50),
	HSP_LOGIN_CPF_CHAR CHAR(11),
	HSP_LOGIN_SENHA_STR VARCHAR(50),
	HSP_CELULAR_STR CHAR(15),
	--HSP_ID_ENDERECO_INT INT,
	HSP_EXCLUIDO_BIT BIT
	
	--PRIMARY KEY
	CONSTRAINT PK_HSP_ID_INT PRIMARY KEY(HSP_ID_INT),
	
	--UNIQUE
	CONSTRAINT UK_HSP_CPF_CHAR UNIQUE(HSP_CPF_CHAR),
	CONSTRAINT UK_HSP_EMAIL_STR UNIQUE(HSP_EMAIL_STR),
	CONSTRAINT UK_HSP_LOGIN_CPF_CHAR UNIQUE(HSP_LOGIN_CPF_CHAR),
	
	--FOREIGN KEY
	--CONSTRAINT FK_HSP_ID_ENDERECO_INT FOREIGN KEY(HSP_ID_ENDERECO_INT)
	--REFERENCES ENDERECO(END_ID_ENDERECO_INT)
);


DROP TABLE IF EXISTS ENDERECO;

CREATE TABLE ENDERECO
(
	END_ID_ENDERECO_INT INT NOT NULL IDENTITY(1,1),
	END_CEP_CHAR CHAR(8),
	END_LOGRADOURO_STR VARCHAR(255),
	END_NUMERO_INT INT,
	END_COMPLEMENTO_STR VARCHAR(255),
	END_BAIRRO_STR VARCHAR(255),
	END_CIDADE_STR VARCHAR(255),
	END_ESTADO_STR VARCHAR(255),
	END_PAIS_STR VARCHAR(255),
	END_ID_HOSPEDE_INT INT, -- FOREIGN KEY
	END_EXCLUIDO_BIT BIT
	
	--PK
	CONSTRAINT PK_END_ID_ENDERECO_INT PRIMARY KEY(END_ID_ENDERECO_INT)
);